### ISSUE TITLE
Generator: Try json-editor

### ISSUE THREAD

**Issue by andibraeu** [freifunk/api.freifunk.net#145]
this one also supports json schema 4 and a lot of other features

https://github.com/jdorn/json-editor

**Comment by christian-weiss** [comment]
https://github.com/jdorn/json-editor is deprecated and not maintained anymore.
Replacement is: https://github.com/json-editor/json-editor
But this json-editor has support for draft-3 and draft-4 schemas only. Not for the latest draft-7 schemas.

We should switch to jsonforms.io JsonForms which uses AJV (https://github.com/epoberezkin/ajv with draft-4, draft-6 and draft-7 support).

Lets continue the discussion in: https://github.com/freifunk/api.freifunk.net/issues/151.
Please close this issue here.
