### ISSUE TITLE
directory.json distribution

### ISSUE THREAD

**Issue by andibraeu** [freifunk/api.freifunk.net#53]
distribute our directory all over the network and make it accessible via one address

goal: make our directory high available, so scripts and website can work with it, use the last valid version from github

add-on: also distribute a file created by the collector containing all aggregated json files

waiting for discussions and suggestions

**Comment by christian-weiss** [comment]
This is a very old ticket. I think it is no longer valid and should be closed.

Most up-to-date directory.json is available here:
https://github.com/freifunk/directory.api.freifunk.net/blob/master/directory.json

Or as RAW data:
https://raw.githubusercontent.com/freifunk/directory.api.freifunk.net/master/directory.json

Many scripts are already using that URL and github takes care that it is high available.
Im my opinion it do not make sense to mirror that at own servers or "own" CDNs.
Independent from that each script / client is allowed to manage a local cache.

Please close the ticket.

**Comment by christian-weiss** [comment]
This issue is solved by github CDN (see above).
Stategies for local caching (at API client side) is out of scope of the API directory issue tracker.

@andibraeu please close this issue.

**Comment by andibraeu** [comment]
github doesn't want to be used as CDN. Most scripts don't use the directory itself, I think. There's the summarized file, containing all api content available: https://api.freifunk.net/data/ffSummarizedDir.json

**Comment by christian-weiss** [comment]
Why should we try to make a file (directory.json) high available, if it is already high available?

I think this issue is wrong here at api.freifunk.net issue tracker as it belongs to directory.api.freifunk.net git repo (issue tracker). Lets close it here and open it at directory.api.freifunk.net (with reference to here) if there is still the need to continue the discussion.

If we recommend to API clients developers to use https://api.freifunk.net/data/ffSummarizedDir.json in favor to directory.json+crawling then ffSummarizedDir.json should be mentioned/recommended in https://github.com/freifunk/directory.api.freifunk.net/blob/master/README.md. We can also suggest to do local caching at API client side (use HTTP GET If-Modified-Since to refresh). 

We should file a ticket at https://github.com/freifunk/common.api.freifunk.net/issues to make ffSummarizedDir.json high available. I would vote for pushing it to github every day / on change - would be interesting to use its change history sometimes (in addition to github CDN). Readme should link to "up-to-date result" of collector (https://api.freifunk.net/data/ffSummarizedDir.json). We can also suggest to do local caching at API client side (use HTTP GET If-Modified-Since to refresh).
